import {
  Activity,
  BadgeCheck,
  BookOpen,
  Bot,
  Boxes,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CarFront,
  Compass,
  Cpu,
  FileText,
  Fingerprint,
  Folder,
  Globe2,
  GraduationCap,
  Grid3X3,
  Handshake,
  Languages,
  Leaf,
  MessagesSquare,
  Microscope,
  Network,
  Orbit,
  PenLine,
  Presentation,
  Route,
  ScanEye,
  ScanSearch,
  Search,
  Sparkles,
  Star,
  Telescope,
  UserRound,
  Users,
  Workflow,
} from "lucide-react";
import type { IconLookup } from "../types/archive";

export const iconLookup: IconLookup = {
  activity: Activity,
  "badge-check": BadgeCheck,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  "brain-circuit": BrainCircuit,
  "briefcase-business": BriefcaseBusiness,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  "car-front": CarFront,
  compass: Compass,
  cpu: Cpu,
  "file-text": FileText,
  fingerprint: Fingerprint,
  folder: Folder,
  "graduation-cap": GraduationCap,
  "globe-2": Globe2,
  grid: Grid3X3,
  handshake: Handshake,
  languages: Languages,
  leaf: Leaf,
  "messages-square": MessagesSquare,
  microscope: Microscope,
  network: Network,
  orbit: Orbit,
  "pen-line": PenLine,
  presentation: Presentation,
  route: Route,
  "scan-eye": ScanEye,
  "scan-search": ScanSearch,
  search: Search,
  sparkles: Sparkles,
  star: Star,
  telescope: Telescope,
  "user-round": UserRound,
  users: Users,
  workflow: Workflow,
};
